// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Emit(arg1:any):Promise<void>;

export function GetAsset(arg1:string):Promise<any>;

export function GetSnapshot(arg1:string):Promise<any>;

export function Greet(arg1:string):Promise<string>;

export function IsReady():Promise<boolean>;

export function Subscribe(arg1:string):Promise<boolean>;
