// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Emit(arg1) {
  return window['go']['main']['App']['Emit'](arg1);
}

export function GetAsset(arg1) {
  return window['go']['main']['App']['GetAsset'](arg1);
}

export function GetSnapshot(arg1) {
  return window['go']['main']['App']['GetSnapshot'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function IsReady() {
  return window['go']['main']['App']['IsReady']();
}

export function Subscribe(arg1) {
  return window['go']['main']['App']['Subscribe'](arg1);
}
